### ISSUE TITLE
Little feedback on the readme

### ISSUE THREAD

**Issue by abhn** [projectlumos/project-lumos-backend#16]
Amazing work with the readme. My very little experience with opensource projects suggests a few changes that can be made to enhance the overall feel of the documentation, which is essentially the entire project for an outsider.

- an index is very important, with links to the appropriate sections
- keep three target audience in mind; 1. the end users. 2. the geeks who'll want to know more about the implementation/tech and 3. the code contributors
   - For end users, a nice section of features, screenshots and 'marketing' oriented content is needed (those nice travis, licence badges can go here). 
   - For geeks, a section of how the app is implemented on an architectural level is a good idea. It may include things like technologies used, how to set up the local server, link by line installation details and details on consuming the api.
   - For the contributors, a little section on project license, what are the future prospects, what lies in the team's todo list can be added. Code conventions that we're following (doesn't have to be 'right' or 'best' can be added here, like what does in what file).

I suggest you to check out readmes of popular projects. Here's one that came to my mind: https://github.com/facebook/react 

Given the length of the current readme, we can split this into README, DOCS and CONTRIB files for better segregation.

**Comment by darth-dodo** [comment]
First iteration up in readme
